name: Leandro Novak
#description:
#meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://leandronovak.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://leandronovak.github.io/blog/'
author:         'Leandro Novak'
